import type { Metadata } from 'next'
import './globals.css'
import { Inter } from 'next/font/google'

import AuthProvider from '@/components/AuthProvider'

import 'photoswipe/dist/photoswipe.css'

export const inter = Inter({ subsets: ['latin'] })
// import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from 'react-toastify'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={`${inter.className} ${inter.className} antialiased layout bg-[#EFF6FF]`}
        >
          <main>{children}</main>
          <ToastContainer />
        </body>
      </html>
    </AuthProvider>
  )
}
